package com.mycompany.planificadorprocesos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Felipe
 */
public class InterfazInformacion extends javax.swing.JFrame {

    /**
     * Creates new form IntefazInformacion
     */
    Planificadores planificador;

    public InterfazInformacion(int quantum, Lista<Proceso> lista1, Lista<Proceso> lista2, Lista<Proceso> lista3, Lista<Proceso> lista4) {
        initComponents();
        terminado = false;
        etiquetaNoExisteProcesoPrioridad.setVisible(false);
        etiquetaNoExisteProcesoBloquear.setVisible(false);
        listaP1 = lista1;
        listaP2 = lista2;
        listaP3 = lista3;
        listaP4 = lista4;
        Quantum = quantum;
        planificador = new Planificadores(Quantum, listaP1, listaP2, listaP3, listaP4, procesosFinalizados, procesosBloqueados);

        timer.start();
    }

    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {

            loop(planificador);
            // Aquí el código que queramos ejecutar.
        }
    });

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        procesoEjecucionId = new javax.swing.JTextField();
        procesoTR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        colaEjecucion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBloqueados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFinalizados = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaListos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cambiarPrioPrio = new javax.swing.JSpinner();
        cambiarPrioId = new javax.swing.JSpinner();
        bloquearProcesoId = new javax.swing.JSpinner();
        botonCambiarPrioridad = new javax.swing.JButton();
        botonBloquearProceso = new javax.swing.JButton();
        procesoTRES = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        etiquetaNoExisteProcesoPrioridad = new javax.swing.JLabel();
        etiquetaNoExisteProcesoBloquear = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proceso en ejecución:");

        jLabel2.setText("ID");

        jLabel3.setText("Tiempo restante");

        procesoEjecucionId.setEditable(false);
        procesoEjecucionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesoEjecucionIdActionPerformed(evt);
            }
        });

        procesoTR.setEditable(false);
        procesoTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesoTRActionPerformed(evt);
            }
        });

        jLabel4.setText("Cola en ejecución:");

        colaEjecucion.setEditable(false);
        colaEjecucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaEjecucionActionPerformed(evt);
            }
        });

        tablaBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "T/Bloqueo", "Prioridad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaBloqueados);

        tablaFinalizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaFinalizados);

        tablaListos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Prioridad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaListos);

        jLabel5.setText("Cola de listos");

        jLabel6.setText("Cola de bloqueados");

        jLabel7.setText("Cola de finalizados");

        jLabel8.setText("Cambiar prioridad");

        jLabel9.setText("Bloquear proceso");

        jLabel10.setText("ID");

        jLabel11.setText("ID");

        jLabel12.setText("Prioridad");

        cambiarPrioPrio.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        cambiarPrioId.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        bloquearProcesoId.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        botonCambiarPrioridad.setText("Cambiar");
        botonCambiarPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPrioridadActionPerformed(evt);
            }
        });

        botonBloquearProceso.setText("Bloquear");
        botonBloquearProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBloquearProcesoActionPerformed(evt);
            }
        });

        procesoTRES.setEditable(false);
        procesoTRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesoTRESActionPerformed(evt);
            }
        });

        jLabel13.setText("Tiempo restante para bloqueo");

        etiquetaNoExisteProcesoPrioridad.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaNoExisteProcesoPrioridad.setText("no existe procesos con ese ID");

        etiquetaNoExisteProcesoBloquear.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaNoExisteProcesoBloquear.setText("no existe procesos con ese ID");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(procesoTRES, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVolver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cambiarPrioId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloquearProcesoId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(botonBloquearProceso)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cambiarPrioPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonCambiarPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etiquetaNoExisteProcesoBloquear)
                                            .addComponent(etiquetaNoExisteProcesoPrioridad))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(176, 176, 176))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(80, 80, 80))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(43, 43, 43)
                                                .addComponent(procesoEjecucionId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(procesoTR, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3))))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel10)
                                .addGap(96, 96, 96)
                                .addComponent(jLabel12)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(colaEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(procesoEjecucionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procesoTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procesoTRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(colaEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cambiarPrioPrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cambiarPrioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCambiarPrioridad)
                            .addComponent(etiquetaNoExisteProcesoPrioridad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(bloquearProcesoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBloquearProceso)
                    .addComponent(etiquetaNoExisteProcesoBloquear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procesoEjecucionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesoEjecucionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procesoEjecucionIdActionPerformed

    private void procesoTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesoTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procesoTRActionPerformed

    private void colaEjecucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaEjecucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaEjecucionActionPerformed

    private void botonCambiarPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarPrioridadActionPerformed
        int id = Integer.parseInt(cambiarPrioId.getValue().toString());
        Nodo<Proceso> nodo;
        if (colaEnTrabajo == 0) {
            nodo = listaP1.buscar(id);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP1);
                etiquetaNoExisteProcesoPrioridad.setVisible(false);
            }
        } else if (colaEnTrabajo == 1) {
            nodo = listaP2.buscar(id);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP1);
                etiquetaNoExisteProcesoPrioridad.setVisible(false);
            }
        } else if (colaEnTrabajo == 2) {
            nodo = listaP3.buscar(id);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP1);
                etiquetaNoExisteProcesoPrioridad.setVisible(false);
            }
        } else if (colaEnTrabajo == 3) {
            nodo = listaP4.buscar(id);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP1);
                etiquetaNoExisteProcesoPrioridad.setVisible(false);
            }
        } else {
            etiquetaNoExisteProcesoPrioridad.setVisible(true);
        }

    }//GEN-LAST:event_botonCambiarPrioridadActionPerformed

    private void botonBloquearProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBloquearProcesoActionPerformed
        int id = Integer.parseInt(bloquearProcesoId.getValue().toString());
        Nodo<Proceso> nodo = null;
        System.out.println("boton");
        if (colaEnTrabajo == 0) {
            nodo = listaP1.buscar(id);
            System.out.println("lista" + listaP1.imprimir());
            System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaa");
            System.out.println(nodo == null);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP1);
                etiquetaNoExisteProcesoBloquear.setVisible(true);
            } else {
                etiquetaNoExisteProcesoBloquear.setVisible(true);
            }
        } else if (colaEnTrabajo == 1) {
            nodo = listaP2.buscar(id);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP2);
                etiquetaNoExisteProcesoBloquear.setVisible(false);
            } else {
                etiquetaNoExisteProcesoBloquear.setVisible(true);
            }
        } else if (colaEnTrabajo == 2) {
            nodo = listaP3.buscar(id);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP3);
                etiquetaNoExisteProcesoBloquear.setVisible(false);
            } else {
                etiquetaNoExisteProcesoBloquear.setVisible(true);
            }
        } else if (colaEnTrabajo == 3) {
            nodo = listaP4.buscar(id);
            if (nodo != null) {
                procesosBloqueados.bloquear(nodo, listaP4);
                etiquetaNoExisteProcesoBloquear.setVisible(false);
            } else {
                etiquetaNoExisteProcesoBloquear.setVisible(true);
            }
        }
    }//GEN-LAST:event_botonBloquearProcesoActionPerformed

    private void procesoTRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesoTRESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procesoTRESActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    public void loop(Planificadores planificador) {
        ;

        if (colaEnTrabajo == 0) {
            colaEjecucion.setText("Cola 1 (procesos del sistema)");
            if (listaP1.esVacia() && procesosBloqueados.esVacia()) {
                colaEnTrabajo++;
                DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
                int filasb = dt2.getRowCount();
                for (int i = filasb - 1; i >= 0; i--) {
                    dt2.removeRow(i);
                }
            }
            Proceso p = planificador.evenDriven(listaP1);
            if (p != null) {
                procesoEjecucionId.setText(String.valueOf(p.ID));
                procesoTR.setText(String.valueOf(p.Duracion));
                if (p.TEntreES >= 0) {
                    procesoTRES.setText(String.valueOf(p.TEntreES));
                } else {
                    procesoTRES.setText("0");
                }
            }

            Nodo<Proceso> actual = listaP1.getPrimero();
            DefaultTableModel dt1 = (DefaultTableModel) tablaListos.getModel();
            int filas = dt1.getRowCount();
            for (int i = filas - 1; i >= 0; i--) {
                dt1.removeRow(i);
            }
            if (actual != null) {
                String[] datos = {
                    String.valueOf(actual.getDato().ID),
                    actual.getDato().Tipo,
                    String.valueOf(actual.getDato().Prioridad),};
                dt1.addRow(datos);
                while (actual.getSiguiente() != null) {
                    actual = actual.getSiguiente();
                    datos[0] = String.valueOf(actual.getDato().ID);
                    datos[1] = actual.getDato().Tipo;
                    datos[2] = String.valueOf(actual.getDato().Prioridad);
                    dt1.addRow(datos);
                }
            }

            actual = procesosBloqueados.getPrimero();
            DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
            int filasb = dt2.getRowCount();
            for (int i = filasb - 1; i >= 0; i--) {
                dt2.removeRow(i);
            }
            if (actual != null) {

                String[] datos1 = {
                    String.valueOf(actual.getDato().ID),
                    String.valueOf(actual.getDato().DuracionES),
                    String.valueOf(actual.getDato().Prioridad),};
                dt2.addRow(datos1);
                while (actual.getSiguiente() != null) {
                    actual = actual.getSiguiente();
                    datos1[0] = String.valueOf(actual.getDato().ID);
                    datos1[1] = String.valueOf(actual.getDato().DuracionES);
                    datos1[2] = String.valueOf(actual.getDato().Prioridad);
                    dt2.addRow(datos1);
                }
            }

            actual = procesosFinalizados.getPrimero();
            if (actual != null) {
                DefaultTableModel dt3 = (DefaultTableModel) tablaFinalizados.getModel();
                int filasf = dt3.getRowCount();
                for (int i = filasf - 1; i >= 0; i--) {
                    dt3.removeRow(i);
                }
                String[] datos2 = {
                    String.valueOf(actual.getDato().ID),
                    actual.getDato().Tipo,};
                dt3.addRow(datos2);
                while (actual.getSiguiente() != null) {
                    actual = actual.getSiguiente();
                    datos2[0] = String.valueOf(actual.getDato().ID);
                    datos2[1] = String.valueOf(actual.getDato().Tipo);
                    dt3.addRow(datos2);
                }
            }

        } //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        if (colaEnTrabajo == 1) {
            colaEjecucion.setText("Cola 2 (procesos de usuario B/CPU)");
            if (listaP2.esVacia() && procesosBloqueados.esVacia()) {
                colaEnTrabajo++;
                DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
                int filasb = dt2.getRowCount();
                for (int i = filasb - 1; i >= 0; i--) {
                    dt2.removeRow(i);
                }
            }

            Proceso pRR = planificador.roundRobin(listaP2, 2);
            if (pRR != null) {
                procesoEjecucionId.setText(String.valueOf(pRR.ID));
                procesoTR.setText(String.valueOf(pRR.Duracion));
                if (pRR.TEntreES >= 0) {
                    procesoTRES.setText(String.valueOf(pRR.TEntreES));
                } else {
                    procesoTRES.setText("0");
                }
            }

            Nodo<Proceso> actualRR = listaP2.getPrimero();
            DefaultTableModel dtRR = (DefaultTableModel) tablaListos.getModel();
            int filasRR = dtRR.getRowCount();
            for (int i = filasRR - 1; i >= 0; i--) {
                dtRR.removeRow(i);
            }
            if (actualRR != null) {
                String[] datos = {
                    String.valueOf(actualRR.getDato().ID),
                    actualRR.getDato().Tipo,
                    String.valueOf(actualRR.getDato().Prioridad),};
                dtRR.addRow(datos);
                while (actualRR.getSiguiente() != null) {
                    actualRR = actualRR.getSiguiente();
                    datos[0] = String.valueOf(actualRR.getDato().ID);
                    datos[1] = actualRR.getDato().Tipo;
                    datos[2] = String.valueOf(actualRR.getDato().Prioridad);
                    dtRR.addRow(datos);
                }
            }

            actualRR = procesosBloqueados.getPrimero();
            DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
            int filasb = dt2.getRowCount();
            for (int i = filasb - 1; i >= 0; i--) {
                dt2.removeRow(i);
            }
            if (actualRR != null) {

                String[] datos1 = {
                    String.valueOf(actualRR.getDato().ID),
                    String.valueOf(actualRR.getDato().DuracionES),
                    String.valueOf(actualRR.getDato().Prioridad),};
                dt2.addRow(datos1);
                while (actualRR.getSiguiente() != null) {
                    actualRR = actualRR.getSiguiente();
                    datos1[0] = String.valueOf(actualRR.getDato().ID);
                    datos1[1] = String.valueOf(actualRR.getDato().DuracionES);
                    datos1[2] = String.valueOf(actualRR.getDato().Prioridad);
                    dt2.addRow(datos1);
                }
            }

            actualRR = procesosFinalizados.getPrimero();
            if (actualRR != null) {
                DefaultTableModel dt3 = (DefaultTableModel) tablaFinalizados.getModel();
                int filasf = dt3.getRowCount();
                for (int i = filasf - 1; i >= 0; i--) {
                    dt3.removeRow(i);
                }
                String[] datos2 = {
                    String.valueOf(actualRR.getDato().ID),
                    actualRR.getDato().Tipo,};
                dt3.addRow(datos2);
                while (actualRR.getSiguiente() != null) {
                    actualRR = actualRR.getSiguiente();
                    datos2[0] = String.valueOf(actualRR.getDato().ID);
                    datos2[1] = String.valueOf(actualRR.getDato().Tipo);
                    dt3.addRow(datos2);
                }
            }
        }
        //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        if (colaEnTrabajo == 2) {
            colaEjecucion.setText("Cola 3 (procesos de usuario B/ES)");
            if (listaP3.esVacia() && procesosBloqueados.esVacia()) {
                colaEnTrabajo++;
                DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
                int filasb = dt2.getRowCount();
                for (int i = filasb - 1; i >= 0; i--) {
                    dt2.removeRow(i);
                }
            }
            Proceso pRR2 = planificador.roundRobin(listaP3, 3);
            if (pRR2 != null) {
                procesoEjecucionId.setText(String.valueOf(pRR2.ID));
                procesoTR.setText(String.valueOf(pRR2.Duracion));
                if (pRR2.TEntreES >= 0) {
                    procesoTRES.setText(String.valueOf(pRR2.TEntreES));
                } else {
                    procesoTRES.setText("0");
                }
            }

            Nodo<Proceso> actualRR2 = listaP3.getPrimero();
            DefaultTableModel dtRR2 = (DefaultTableModel) tablaListos.getModel();
            int filasRR2 = dtRR2.getRowCount();
            for (int i = filasRR2 - 1; i >= 0; i--) {
                dtRR2.removeRow(i);
            }
            if (actualRR2 != null) {
                String[] datos = {
                    String.valueOf(actualRR2.getDato().ID),
                    actualRR2.getDato().Tipo,
                    String.valueOf(actualRR2.getDato().Prioridad),};
                dtRR2.addRow(datos);
                while (actualRR2.getSiguiente() != null) {
                    actualRR2 = actualRR2.getSiguiente();
                    datos[0] = String.valueOf(actualRR2.getDato().ID);
                    datos[1] = actualRR2.getDato().Tipo;
                    datos[2] = String.valueOf(actualRR2.getDato().Prioridad);
                    dtRR2.addRow(datos);
                }
            }

            actualRR2 = procesosBloqueados.getPrimero();
            DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
            int filasb = dt2.getRowCount();
            for (int i = filasb - 1; i >= 0; i--) {
                dt2.removeRow(i);
            }
            if (actualRR2 != null) {

                String[] datos1 = {
                    String.valueOf(actualRR2.getDato().ID),
                    String.valueOf(actualRR2.getDato().DuracionES),
                    String.valueOf(actualRR2.getDato().Prioridad),};
                dt2.addRow(datos1);
                while (actualRR2.getSiguiente() != null) {
                    actualRR2 = actualRR2.getSiguiente();
                    datos1[0] = String.valueOf(actualRR2.getDato().ID);
                    datos1[1] = String.valueOf(actualRR2.getDato().DuracionES);
                    datos1[2] = String.valueOf(actualRR2.getDato().Prioridad);
                    dt2.addRow(datos1);
                }
            }

            actualRR2 = procesosFinalizados.getPrimero();
            if (actualRR2 != null) {
                DefaultTableModel dt3 = (DefaultTableModel) tablaFinalizados.getModel();
                int filasRR22 = dt3.getRowCount();
                for (int i = filasRR22 - 1; i >= 0; i--) {
                    dt3.removeRow(i);
                }
                String[] datos2 = {
                    String.valueOf(actualRR2.getDato().ID),
                    actualRR2.getDato().Tipo,};
                dt3.addRow(datos2);
                while (actualRR2.getSiguiente() != null) {
                    actualRR2 = actualRR2.getSiguiente();
                    datos2[0] = String.valueOf(actualRR2.getDato().ID);
                    datos2[1] = String.valueOf(actualRR2.getDato().Tipo);
                    dt3.addRow(datos2);
                }
            }

        } //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        //-----------------------------------------------------------------------------------------------------
        if (colaEnTrabajo == 3) {
            if (listaP4.esVacia() && procesosBloqueados.esVacia()) {
                colaEjecucion.setText("Cola 4 (procesos Batch)");
                colaEnTrabajo = 0;
                DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
                int filasb = dt2.getRowCount();
                for (int i = filasb - 1; i >= 0; i--) {
                    dt2.removeRow(i);
                }
            }

            Proceso pF = planificador.firstComeFirstServed(listaP4);
            if (pF != null) {
                procesoEjecucionId.setText(String.valueOf(pF.ID));
                procesoTR.setText(String.valueOf(pF.Duracion));
                if (pF.TEntreES >= 0) {
                    procesoTRES.setText(String.valueOf(pF.TEntreES));
                } else {
                    procesoTRES.setText("0");
                }
            }

            Nodo<Proceso> actualf = listaP4.getPrimero();
            DefaultTableModel dtf = (DefaultTableModel) tablaListos.getModel();
            int filasff = dtf.getRowCount();
            for (int i = filasff - 1; i >= 0; i--) {
                dtf.removeRow(i);
            }
            if (actualf != null) {
                String[] datos = {
                    String.valueOf(actualf.getDato().ID),
                    actualf.getDato().Tipo,
                    String.valueOf(actualf.getDato().Prioridad),};
                dtf.addRow(datos);
                while (actualf.getSiguiente() != null) {
                    actualf = actualf.getSiguiente();
                    datos[0] = String.valueOf(actualf.getDato().ID);
                    datos[1] = actualf.getDato().Tipo;
                    datos[2] = String.valueOf(actualf.getDato().Prioridad);
                    dtf.addRow(datos);
                }
            }

            actualf = procesosBloqueados.getPrimero();
            DefaultTableModel dt2 = (DefaultTableModel) tablaBloqueados.getModel();
            int filasb = dt2.getRowCount();
            for (int i = filasb - 1; i >= 0; i--) {
                dt2.removeRow(i);
            }
            if (actualf != null) {
                String[] datos1 = {
                    String.valueOf(actualf.getDato().ID),
                    String.valueOf(actualf.getDato().DuracionES),
                    String.valueOf(actualf.getDato().Prioridad),};
                dt2.addRow(datos1);
                while (actualf.getSiguiente() != null) {
                    actualf = actualf.getSiguiente();
                    datos1[0] = String.valueOf(actualf.getDato().ID);
                    datos1[1] = String.valueOf(actualf.getDato().DuracionES);
                    datos1[2] = String.valueOf(actualf.getDato().Prioridad);
                    dt2.addRow(datos1);
                }
            }

            actualf = procesosFinalizados.getPrimero();
            if (actualf != null) {
                DefaultTableModel dt3 = (DefaultTableModel) tablaFinalizados.getModel();
                int filasf = dt3.getRowCount();
                for (int i = filasf - 1; i >= 0; i--) {
                    dt3.removeRow(i);
                }
                String[] datos2 = {
                    String.valueOf(actualf.getDato().ID),
                    actualf.getDato().Tipo,};
                dt3.addRow(datos2);
                while (actualf.getSiguiente() != null) {
                    actualf = actualf.getSiguiente();
                    datos2[0] = String.valueOf(actualf.getDato().ID);
                    datos2[1] = String.valueOf(actualf.getDato().Tipo);
                    dt3.addRow(datos2);
                }
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    int colaEnTrabajo = 0;
    Lista<Proceso> listaP1 = new Lista();
    Lista<Proceso> listaP2 = new Lista();
    Lista<Proceso> listaP3 = new Lista();
    Lista<Proceso> listaP4 = new Lista();
    Lista<Proceso> procesosFinalizados = new Lista();
    Lista<Proceso> procesosBloqueados = new Lista();
    int Quantum;
    boolean terminado;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bloquearProcesoId;
    private javax.swing.JButton botonBloquearProceso;
    private javax.swing.JButton botonCambiarPrioridad;
    private javax.swing.JButton botonVolver;
    private javax.swing.JSpinner cambiarPrioId;
    private javax.swing.JSpinner cambiarPrioPrio;
    private javax.swing.JTextField colaEjecucion;
    private javax.swing.JLabel etiquetaNoExisteProcesoBloquear;
    private javax.swing.JLabel etiquetaNoExisteProcesoPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField procesoEjecucionId;
    private javax.swing.JTextField procesoTR;
    private javax.swing.JTextField procesoTRES;
    private javax.swing.JTable tablaBloqueados;
    private javax.swing.JTable tablaFinalizados;
    private javax.swing.JTable tablaListos;
    // End of variables declaration//GEN-END:variables
}
